version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4023:4023
    networks:
      - samagra_compass

networks:
  samagra_compass:
    external: true